---
loader: taskgraph.loader.transform:loader
transforms:
    - taskgraph.transforms.index_search:transforms
    - taskgraph.transforms.task:transforms

jobs:
    linux64-minidump-stackwalk:
        description: "minidump_stackwalk toolchain"
        index-search:
            - gecko.cache.level-3.toolchains.v3.linux64-minidump-stackwalk.latest
    browsertime:
        description: "Browsertime toolchain"
        index-search:
            - gecko.cache.level-3.toolchains.v3.browsertime.latest
    linux64-node:
        description: "Node.js toolchain"
        index-search:
            - gecko.cache.level-3.toolchains.v3.linux64-node-10.latest
    linux64-geckodriver:
        description: "Geckodriver toolchain"
        index-search:
            - gecko.cache.level-3.toolchains.v3.linux64-geckodriver.latest
